FROM golang:1.24.4-alpine3.22 AS builder

WORKDIR /app
COPY . .

USER root

RUN apk add --no-cache git && \
    go mod tidy && \
    go build -o server main.go

# Final image
FROM christy712/alpine-chrome:latest

USER root

# Use a more reliable writable directory
WORKDIR /usr/src/app

# Create output directory inside container
RUN mkdir -p output

# Copy the Go binary from builder
COPY --from=builder /app/server /usr/local/bin/server

EXPOSE 8080
ENTRYPOINT ["server"]
